language: minimal

services: docker

before_install:
  - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

install:
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel

after_success:
  - docker push opetion/reverseproxy
  - docker push opetion/udacity-restapi-user
  - docker push opetion/udacity-restapi-feed
  - docker push opetion/udacity-frontend:local
